[package]
name = "lodisdb"
version = "0.1.2"
authors = ["PeterDing <dfhayst@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
rocksdb = "0.16"
rand = "0.8"
